#!/bin/bash
#====================================================
#
#  Modificaciones Al Codigo: Elijah_ssh
#  https://t.me/Elijahssh
#
#====================================================
cat /dev/null > ~/.bash_history && history -c
barra="\033[0m\e[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
x="ok"
IP=$(wget -qO- ipv4.icanhazip.com)
while true $x != "ok"
do
clear
if [ ! -e /home/keyscript ]; then
    mkdir /home/keyscript
fi
key_tmp="$RANDOM:$RANDOM"
a="$RANDOM"
b="$RANDOM"
echo "$a" > /tmp/a
echo "$b" > /tmp/b
pasta1=$(cat /tmp/a)
pasta2=$(cat /tmp/b)
signus=":"

mine_port () {
unset portas
portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
i=0
while read port; do
var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
[[ "$(echo -e ${portas[@]}|grep "$var1 $var2")" ]] || {
    portas[$i]="$var1 $var2"
    let i++
    }
done <<< "$portas_var"
for((i=0; i<=${#portas[@]}; i++)); do
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && break
texto="\033[1;31m ${servico}: \033[1;32m${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -ne "${texto}"
let i++
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && {
   echo -e " "
   break
   }
texto="\033[1;31m ${servico}: \033[1;32m${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -ne "${texto}"
let i++
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && {
   echo -e " "
   break
   }
texto="\033[1;31m ${servico}: \033[1;32m${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -e "${texto}"
done
}

fun_gerkey () {
echo ""
echo -ne "\033[1;36mInfome o nome do Cliente:\033[1;37m "; read client
if [[ -z $client ]]; then
   echo -e "\033[1;31m Nome invalido ou vazio\033[0m"
   sleep 2
   exit 0
fi
echo ""
echo -ne "\033[1;36mQuantos minutos essa key deve durar\033[1;33m
(\033[1;31mEX: 20m m=Minutos, h=Horas, d=Dias\033[1;33m)\033[1;37m: "; read _temp
if [[ -z $_temp ]]; then
   echo -e "\033[1;31m Tempo invalido ou vazio\033[0m"
   sleep 2
   exit 0
fi
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
[[ ! -e /var/www/index.html ]] && touch /var/www/index.html > /dev/null 2>&1
mkdir /var/www/$pasta1
mkdir /var/www/$pasta1/$pasta2
touch /home/keyscript/$client
cp /home/lisa /var/www/$pasta1/$pasta2/lisa
cp -a /home/_script_$/. /var/www/$pasta1
chmod 777 /var/www/$pasta1/crz/*
sed -i "s/INFO_AK/$pasta1/g" /var/www/html/$pasta1/$pasta2/lisa>/dev/null 2>&1
shc -v -r -f /var/www/html/$pasta1/$pasta2/lisa
rm /var/www/html/$pasta1/$pasta2/lisa
rm /var/www/html/$pasta1/$pasta2/lisa.x.c
mv /var/www/html/$pasta1/$pasta2/lisa.x /var/www/html/$pasta1/$pasta2/lisa
cp /home/Get /var/www/html/promax/Get
cp /home/Pro /var/www/html/Pro
else
[[ ! -e /var/www/html/index.html ]] && touch /var/www/html/index.html > /dev/null 2>&1
mkdir /var/www/html/$pasta1
mkdir /var/www/html/$pasta1/$pasta2
touch /home/keyscript/$client
cp /home/lisa /var/www/html/$pasta1/$pasta2/lisa
cp -a /home/_script_$/. /var/www/html/$pasta1
chmod 777 /var/www/html/$pasta1/crz/*
sed -i "s/INFO_AK/$pasta1/g" /var/www/html/$pasta1/$pasta2/lisa>/dev/null 2>&1
shc -v -r -f /var/www/html/$pasta1/$pasta2/lisa
rm /var/www/html/$pasta1/$pasta2/lisa
rm /var/www/html/$pasta1/$pasta2/lisa.x.c
mv /var/www/html/$pasta1/$pasta2/lisa.x /var/www/html/$pasta1/$pasta2/lisa
cp /home/Get /var/www/html/promax/Get
cp /home/Pro /var/www/html/Pro
fi
clear
echo -e "\033[0;34m============================"
echo -e "\033[1;33m🌐 SCRIPT SSH PRO MAX 🌐    \033[0m"
echo -e "\033[0;34m============================"
echo ""
echo -e "\033[1;37mapt-get update -y; apt-get upgrade -y; wget $IP/scripts/Plus; chmod 777 Plus; ./Plus"
echo ""
echo -e "\033[1;32mKEY: \033[1;37m$pasta1$signus$pasta2\033[0m"
echo ""
#echo -e "\033[0;34m============================"
#echo -e "\033[1;33mTUTORIAL DE INSTALAÇÃO !    \033[0m"
echo -e "\033[0;34m============================"
echo -e "\033[1;33mObrigado Pela Sua Contribuicao! 👍
BY: ELIJAHSSH ✌️😎 \033[0m"
echo ""
echo -e "\033[1;32mUsuario: \033[1;37m $client\033[0m"
echo -e "\033[1;32mValidade: \033[1;37m$_temp\033[0m"
echo -e "\033[1;32mVersao: \033[1;37m  $(cat /home/_script_$/crz/versao)\033[0m"
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
echo "#!/bin/bash
#NAME: $client
#KEY: $pasta1$signus$pasta2
#VALIDADE: $_temp
sleep $_temp
rm -rf /var/www/pasta1
rm -rf /var/www/html/promax/Get
rm -rf /var/www/html/Pro
rm -rf /home/keyscript/$client
rm -rf /home/keyscript/$client
exit" > /home/keyscript/$client
else
echo "#!/bin/bash
#NAME: $client
#KEY: $pasta1$signus$pasta2
#VALIDADE: $_temp
sleep $_temp
rm -rf /var/www/html/$pasta1
rm -rf /var/www/html/promax/Get
rm -rf /var/www/html/Pro
rm -rf /home/keyscript/$client
exit" > /home/keyscript/$client
fi
bash /home/keyscript/$client &
}

fun_gerkey_fixa () {
echo ""
echo -ne "\033[1;36mInfome o nome do Cliente:\033[1;37m "; read client
if [[ -z $client ]]; then
   echo -e "\033[1;31m Nome invalido ou vazio\033[0m"
   sleep 2
   exit 0
fi
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
mkdir /var/www/$pasta1
mkdir /var/www/$pasta1/$pasta2
touch /home/keyscript/$client
cp /home/lisa /var/www/$pasta1/$pasta2/lisa
cp -a /home/_script_$/. /var/www/$pasta1
chmod 777 /var/www/$pasta1/crz/*
sed -i "s/INFO_AK/$pasta1/g" /var/www/html/$pasta1/$pasta2/lisa>/dev/null 2>&1
shc -v -r -f /var/www/html/$pasta1/$pasta2/lisa
rm /var/www/html/$pasta1/$pasta2/lisa
rm /var/www/html/$pasta1/$pasta2/lisa.x.c
mv /var/www/html/$pasta1/$pasta2/lisa.x /var/www/html/$pasta1/$pasta2/lisa
cp /home/Get /var/www/html/promax/Get
cp /home/Pro /var/www/html/Pro
else
[[ ! -e /var/www/html/index.html ]] && touch /var/www/html/index.html > /dev/null 2>&1
mkdir /var/www/html/$pasta1
mkdir /var/www/html/$pasta1/$pasta2
touch /home/keyscript/$client
cp /home/lisa /var/www/html/$pasta1/$pasta2/lisa
cp -a /home/_script_$/. /var/www/html/$pasta1
chmod 777 /var/www/html/$pasta1/crz/*
sed -i "s/INFO_AK/$pasta1/g" /var/www/html/$pasta1/$pasta2/lisa>/dev/null 2>&1
shc -v -r -f /var/www/html/$pasta1/$pasta2/lisa
rm /var/www/html/$pasta1/$pasta2/lisa
rm /var/www/html/$pasta1/$pasta2/lisa.x.c
mv /var/www/html/$pasta1/$pasta2/lisa.x /var/www/html/$pasta1/$pasta2/lisa
cp /home/Get /var/www/html/promax/Get
cp /home/Pro /var/www/html/Pro
fi
clear
echo -e "\033[0;34m============================"
echo -e "\033[1;33m🌐 SCRIPT SSH PRO MAX 🌐    \033[0m"
echo -e "\033[0;34m============================"
echo ""
echo -e "\033[1;37mapt-get update -y; apt-get upgrade -y; wget $IP/scripts/Plus; chmod 777 Plus; ./Plus"
echo ""
echo -e "\033[1;32mKEY: \033[1;37m$pasta1$signus$pasta2\033[0m"
echo ""
#echo -e "\033[0;34m============================"
#echo -e "\033[1;33mTUTORIAL DE INSTALAÇÃO !    \033[0m"
echo -e "\033[0;34m============================"
echo -e "\033[1;33mObrigado Pela Sua Contribuicao! 👍
BY: ELIJAHSSH ✌️😎 \033[0m"
echo ""
echo -e "\033[1;32mUsuario: \033[1;37m $client\033[0m"
echo -e "\033[1;32mValidade: \033[1;37mPermanente\033[0m"
echo -e "\033[1;32mVersao: \033[1;37m  $(cat /home/_script_$/crz/versao)\033[0m"
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
echo "#!/bin/bash
#NAME: $client
#KEY: $pasta1$signus$pasta2
#VALIDADE: $_temp
rm -rf /var/www/$pasta1
rm -rf /var/www/html/promax/Get
rm -rf /var/www/html/Pro
rm -rf /home/keyscript/$client
exit" > /home/keyscript/$client
else
echo "#!/bin/bash
#NAME: $client
#KEY: $pasta1$signus$pasta2
#VALIDADE: $_temp
rm -rf /var/www/html/$pasta1
rm -rf /var/www/html/promax/Get
rm -rf /var/www/html/Pro
rm -rf /home/keyscript/$client
exit" > /home/keyscript/$client
fi
# bash /home/keyscript/$client &
}

fun_gerkey_manual () {
echo ""
echo -ne "\033[1;36mInfome o nome do Cliente:\033[1;37m "; read client
if [[ -z $client ]]; then
   echo -e "\033[1;31m Nome invalido ou vazio\033[0m"
   sleep 2
   exit 0
fi
echo ""
echo -ne "\033[1;36mQuantos minutos essa key deve durar\033[1;33m
(\033[1;31mEX: \033[1;32m20m m=Minutos, h=Horas, d=Dias\033[1;33m)\033[1;37m: "; read _temp
if [[ -z $_temp ]]; then
   echo -e "\033[1;31m Tempo invalido ou vazio\033[0m"
   sleep 2
   exit 0
fi
echo ""
echo -ne "\033[1;36mDigite a Key [ xxxxxxxx:xxxxxxxx ]\033[1;33m
(\033[1;31mEX: \033[1;32m1234:1234\033[1;33m)\033[1;37m: "; read key
_lnk1=$(echo "$key"|awk -F : '{print $1}')
_lnk2=$(echo "$key"|awk -F : '{print $2}')
echo "$_lnk1" > /tmp/c
echo "$_lnk2" > /tmp/d
key1p=$(cat /tmp/c)
key2p=$(cat /tmp/d)
signus=":"
if [ "$key" = "" ]; then
   echo -e "\033[1;31m key nao alterada\033[0m"
   sleep 2
   exit 0
fi
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
[[ ! -e /var/www/index.html ]] && touch /var/www/index.html > /dev/null 2>&1
[[ ! -d /var/www/$key1p ]] && mkdir /var/www/$key1p
[[ ! -d /var/www/$key1p/$key2p ]] && mkdir /var/www/$key1p/$key2p
touch /home/keyscript/$client
cp /home/lisa /var/www/$key1p/$key2p/lisa
cp -a /home/_script_$/. /var/www/$key1p
chmod 777 /var/www/$key1p/crz/*
sed -i "s/INFO_AK/$key1p/g" /var/www/html/$key1p/$key2p/lisa>/dev/null 2>&1
shc -v -r -f /var/www/html/$key1p/$key2p/lisa
rm /var/www/html/$key1p/$key2p/lisa
rm /var/www/html/$key1p/$key2p/lisa.x.c
mv /var/www/html/$key1p/$key2p/lisa.x /var/www/html/$key1p/$key2p/lisa
cp /home/Get /var/www/html/promax/Get
cp /home/Pro /var/www/html/Pro
else
[[ ! -e /var/www/html/index.html ]] && touch /var/www/html/index.html > /dev/null 2>&1
[[ ! -d /var/www/html/$key1p ]] && mkdir /var/www/html/$key1p
[[ ! -d /var/www/html/$key1p/$key2p ]] && mkdir /var/www/html/$key1p/$key2p
touch /home/keyscript/$client
cp /home/lisa /var/www/html/$key1p/$key2p/lisa
cp -a /home/_script_$/. /var/www/html/$key1p
chmod 777 /var/www/html/$key1p/crz/*
sed -i "s/INFO_AK/$key1p/g" /var/www/html/$key1p/$key2p/lisa>/dev/null 2>&1
shc -v -r -f /var/www/html/$key1p/$key2p/lisa
rm /var/www/html/$key1p/$key2p/lisa
rm /var/www/html/$key1p/$key2p/lisa.x.c
mv /var/www/html/$key1p/$key2p/lisa.x /var/www/html/$key1p/$key2p/lisa
cp /home/Get /var/www/html/promax/Get
cp /home/Pro /var/www/html/Pro
fi
clear
echo -e "\033[0;34m============================"
echo -e "\033[1;33m🌐 SCRIPT SSH PRO MAX 🌐    \033[0m"
echo -e "\033[0;34m============================"
echo ""
echo -e "\033[1;37mapt-get update -y; apt-get upgrade -y; wget $IP/scripts/Plus; chmod 777 Plus; ./Plus"
echo ""
echo -e "\033[1;32mKEY: \033[1;37m$key1p$signus$key2p\033[0m"
echo ""
#echo -e "\033[0;34m============================"
#echo -e "\033[1;33mTUTORIAL DE INSTALAÇÃO !    \033[0m"
echo -e "\033[0;34m============================"
echo -e "\033[1;33mObrigado Pela Sua Contribuicao! 👍
BY: ELIJAHSSH ✌️😎 \033[0m"
echo ""
echo -e "\033[1;32mUsuario: \033[1;37m $client\033[0m"
echo -e "\033[1;32mValidade: \033[1;37m$_temp\033[0m"
echo -e "\033[1;32mVersao: \033[1;37m  $(cat /home/_script_$/crz/versao)\033[0m"
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
echo "#!/bin/bash
#NAME: $client
#KEY: $key1p$signus$key2p
#VALIDADE: $_temp
sleep $_temp
rm -rf /var/www/$key1p
rm -rf /var/www/html/promax/Get
rm -rf /var/www/html/Pro
rm -rf /home/keyscript/$client
exit" > /home/keyscript/$client
else
echo "#!/bin/bash
#NAME: $client
#KEY: $key1p$signus$key2p
#VALIDADE: $_temp
sleep $_temp
rm -rf /var/www/html/$key1p
rm -rf /var/www/html/promax/Get
rm -rf /var/www/html/Pro
rm -rf /home/keyscript/$client
exit" > /home/keyscript/$client
fi
bash /home/keyscript/$client &
}

fun_keyson () {
echo -e "$barra"
echo -e " \033[1;31m++| \033[1;32mKEYS ONLINE \033[1;31m|++ \033[0m"
echo -e "$barra"
echo ""
[ "$(ls -A /home/keyscript)" ] && echo -e "\033[1;32m Key Online!\033[1;37m" || echo -e "\033[1;31m Nenhuma Key Online!\033[0m"
echo ""
ls /home/keyscript
}

fun_delkey () {
echo -e "$barra"
echo -e " \033[1;31m++| \033[1;32mREMOVER KEY ONLINE \033[1;31m|++ \033[0m"
echo -e "$barra"
echo -e "\033[1;33m"
for keyson in $(ls /home/keyscript |sort |sed 's/.sh//g')
do
echo " $keyson"
done
echo ""
echo -ne "\033[1;36m Imforme o nome: \033[1;37m "; read client
if [ -e /home/keyscript/$client ]; then
    tmp=$(cat /home/keyscript/$client | sed -n '2 p')
    sed -i "s/\b$tmp\b/echo -n/g" /home/keyscript/$client > /dev/null 2>&1
    bash /home/keyscript/$client;
    sleep 2
    echo -e "\n\033[1;32m Key Removida Com Sucesso !\033[0m"
    else
    echo -e "\n\033[1;31m Key nao existente !\033[0m"
    sleep 2.5s
fi
}

bots () {
clear
[[ $(screen -list| grep -c 'bot_script') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     ATIVACÃO BOT SCRIPT    \E[0m"
    echo ""
    echo -ne "\n\033[1;32mINFORME O TOKEN\033[1;37m: "; read token
    echo -ne "\033[1;32mINFORME SEU ID:\033[1;37m "; read iduser
    cd /etc/bot
    screen -dmS bot_script ./botscript $token $iduser > /dev/null 2>&1
    clear && echo "BOT ATIVADO"
    keyscript
} || {
    screen -r -S "bot_script" -X quit
    clear && echo "BOT DESATIVADO"
    keyscript
}
}

autoe () {
clear
if grep "keyscript;" /etc/profile > /dev/null; then
      offautkeyscript () {
         sed -i '/keyscript;/d' /etc/profile
      }
      fun_bar 'offautkeyscript'
      echo ""
      echo -e "\033[1;31mAUTO EXECUÇÃO DESATIVADO!\033[0m"
      clear
      keyscript
   else
      autkeyscript () {
         grep -v "^keyscript;" /etc/profile > /tmp/tmpass && mv /tmp/tmpass /etc/profile
         echo "keyscript;" >> /etc/profile
      }
      fun_bar 'autkeyscript'
      echo ""
      echo -e "\033[1;32mAUTO EXECUÇÃO ATIVADO!\033[0m"
      clear
      keyscript
   fi
   }

stsbotteste=$(ps x | grep "bot_script"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
echo -e "$barra"
sts=$([ "$(ls -A /home/keyscript)" ] && echo -e "\033[1;32m Key Online!\033[1;37m" || echo -e "\033[1;31m Nenhuma Key Online!\033[0m")
echo -e "\033[1;37mSTATUS: $sts"
echo -e "$barra"
mine_port
echo -e "$barra"
echo -e " \033[1;31m++| \033[1;32mKEYGEN SSH PRO MAX \033[1;31m|++       \033[1;33m[ VERSAO: 2.0 BETA ]\033[0m"
echo -e "$barra"
echo -e "\033[1;37m |1| \033[1;31m<----> \033[1;36mGERAR KEY ALEATORIA \033[1;32m[CV] \033[0m"
echo -e "\033[1;37m |2| \033[1;31m<----> \033[1;36mGERAR KEY ALEATORIA FIXA \033[1;32m[SV] \033[0m"
echo -e "\033[1;37m |3| \033[1;31m<----> \033[1;36mGERAR KEY MANUAL\033[1;33m ! \033[1;32m[CV] \033[0m"
if [ ! -e /var/www/html/1:8%7o.2sg3-q:5 ]; then
echo -e "\033[1;37m |4| \033[1;31m<----> \033[1;31m(PARADO)\033[1;36m - INICIAR KEYGEN"
else
echo -e "\033[1;37m |4| \033[1;31m<----> \033[1;32m(RODANDO)\033[1;36m - PARAR KEYGEN"
fi
echo -e "\033[1;37m |5| \033[1;31m<----> \033[1;36mKEYS ONLINE\033[0m"
echo -e "\033[1;37m |6| \033[1;31m<----> \033[1;36mREMOVER KEY\033[0m"
#echo -e "\033[1;37m |X| \033[1;31m<----> \033[1;36mLOG DE REGISTROS\033[0m"
echo -e "\033[1;37m |7| \033[1;31m<----> \033[1;33m[ ! ] \033[1;32mACTUALIZAR \033[0m"
echo -e "\033[1;37m |8| \033[1;31m<----> \033[1;33m[ ! ] \033[1;31mDESINSTALAR KEYGEN\033[0m "
echo -e "\033[1;37m |9| \033[1;31m<----> \033[1;36mOTIMIZAR SERVIDOR    \033[1;31mRam:   \033[1;37m $_usor\033[0m"
echo -e "\033[1;37m |10| \033[1;31m<----> \033[1;36mBOT SCRIPT $stsbotteste\033[0m"
echo -e "\033[1;37m |11| \033[1;31m<----> \033[1;36mAUTO EXECUCAO $stsbotteste\033[0m"
echo -e "\033[1;37m |0| \033[1;31m<----> \033[1;36mSAIR DO KEYGEN       \033[1;31mNucleo:\033[1;37m $_usop \033[0m"
echo -e "                           \033[1;37m@Elijahssh\033[0m \033[0m"
echo -e "$barra"
echo -ne "\033[1;32m[0/9]: "; read x

case $x in
1)
fun_gerkey
echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
;;
2)
fun_gerkey_fixa
echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
;;
3)
fun_gerkey_manual
echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
;;
4)
if [ ! -e /var/www/html/1:8%7o.2sg3-q:5 ]; then
#KEYGEN SSH PRO MAX ON
pkill -f 80
apt-get install apache2 -y > /dev/null 2>&1
cp /bin/ports2.conf /etc/apache2/ports2.conf
mv /etc/apache2/ports2.conf /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
echo "#KEYGEN SSH PRO MAX ON" > /var/www/html/1:8%7o.2sg3-q:5
echo ""
echo -e "\033[1;32mIniciado"
echo -e "\033[1;32mRodando Apache2 Porta 80"
else
#KEYGEN SSH PRO MAX OFF
pkill -f 80
cp /bin/ports.conf /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
rm -rf /var/www/html/1:8%7o.2sg3-q:5
echo ""
echo -e "\033[1;31mParado"
echo -e "\033[1;32mRemovido Apache2 Porta 80"
fi
echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
;;
5)
clear
fun_keyson
echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
;;
6)
clear
fun_delkey
echo -e "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"
;;
7)
clear
rm $HOME/instgerador.sh* > /dev/null 2>&1; wget https://raw.githubusercontent.com/KEYXXELIJAHSSHX3/SSHPRO_MAX-GERADOXX2/main/instgerador.sh; chmod 777 instgerador.sh* && ./instgerador.sh*
exit
;;
8)
    rm -rf /home/lisa > /dev/null 2>&1
    rm -rf /home/Get > /dev/null 2>&1
    rm -rf /home/Pro > /dev/null 2>&1
    rm -rf /home/index.html > /dev/null 2>&1
    rm -rf /home/_script_$ > /dev/null 2>&1
    rm -rf /home/keyscript > /dev/null 2>&1 > /dev/null 2>&1
    rm -rf /bin/keyscript > /dev/null 2>&1
    rm -rf /bin/key > /dev/null 2>&1
    rm -rf /bin/otimizar > /dev/null 2>&1
    rm -rf /var/www/html/Index.php > /dev/null 2>&1
    rm -rf /var/www/html/script > /dev/null 2>&1
    rm -rf /var/www/html/promax > /dev/null 2>&1
    rm -rf /var/www/html/1:8%7o.2sg3-q:5 > /dev/null 2>&1
    pkill -f 80
    cp /bin/ports.conf /etc/apache2/ports.conf > /dev/null 2>&1
    service apache2 restart > /dev/null 2>&1
    rm -rf /bin/ports.conf > /dev/null 2>&1
    rm -rf /bin/ports2.conf > /dev/null 2>&1
exit
clear
;;
9)
clear
otimizar
echo -e "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
;;
10)
clear
bots
;;
11)
clear
autoe
;;
0)
echo -ne "\n\033[1;31mSaindo... Enter para SAIR\033[0m"; read
clear
exit
clear
;;
*)
echo -ne "\n\033[1;31mOpcao invalida !\033[0m"; read
ok
;;
esac
done
#fim
cat /dev/null > ~/.bash_history && history -c
